spring.application.name=inventory-service
server.port=8081

spring.config.import=optional:file:../.env[.properties]

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASS}